# Generated by Django 5.1.7 on 2026-06-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminuser_studentuser_teacheruser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='grade_level',
            field=models.IntegerField(blank=True, choices=[(7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10')], null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='id_photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='registration_requests/back/'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='id_photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='registration_requests/front/'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='selfie_photo',
            field=models.ImageField(blank=True, null=True, upload_to='registration_requests/selfie/'),
        ),
    ]
