# Generated by Django 6.0.6 on 2026-06-19 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(db_column='question_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(db_column='text')),
                ('order', models.IntegerField(db_column='order', default=0)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_id', models.UUIDField(db_column='choice_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(db_column='text', max_length=200)),
                ('is_correct', models.BooleanField(db_column='is_correct', default=False)),
                ('question', models.ForeignKey(db_column='question', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question')),
            ],
            options={
                'db_table': 'choices',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.UUIDField(db_column='quiz_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=200)),
                ('description', models.TextField(blank=True, db_column='description')),
                ('time_limit', models.IntegerField(blank=True, db_column='time_limit', help_text='Time limit in minutes', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(db_column='subject', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='subjects.subject')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(db_column='quiz', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
    ]
