# Generated by Django 5.1.7 on 2026-06-24 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(choices=[('english', 'English'), ('math', 'Math'), ('science', 'Science'), ('filipino', 'Filipino')], help_text='Subject category', max_length=20)),
                ('grade_level', models.IntegerField(choices=[(7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10')], help_text='Grade level for this subject')),
                ('name', models.CharField(help_text='Full display name e.g. "English - Grade 7"', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('passing_score', models.IntegerField(default=75, help_text='Minimum score (0-100) required to advance to next grade level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['grade_level', 'subject_code'],
                'unique_together': {('subject_code', 'grade_level')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('final_grade_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_promoted', models.BooleanField(default=False, help_text='True when student passed and was promoted to next grade level')),
                ('student', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='subjects.subject')),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
